name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        uses: actions/heroku@v7
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Login to Heroku
        run: heroku container:login

      - name: Build and push Docker image
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Docker image
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}